server:
  port: 8080  # API Gateway chạy trên cổng 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Tự động định tuyến theo Eureka
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET, POST, PUT, DELETE"
            allowedHeaders: "*"
            allowCredentials: true
      # routes:
      #   #Cấu hình cổng file user-service
      #   - id: user-service
      #     uri: lb://USER-SERVICE
      #     predicates:
      #       - Path=/user-service/**

      #   #Cấu hình cổng file user-service
      #   - id: post-service
      #     uri: lb://POST-SERVICE
      #     predicates:
      #       - Path=/posts/**

      #   #Cấu hình cổng file message-service  
      #   - id: message-service
      #     uri: lb://MESSAGE-SERVICE
      #     predicates:
      #       - Path=/messages/**

      #   #Cấu hình cổng file groupchat-service  
      #   - id: groupchat-service
      #     uri: lb://GROUPCHAT-SERVICE
      #     predicates:
      #       - Path=/groupchats/**

      #   #Cấu hình cổng file friendship-service  
      #   - id: friendship-service
      #     uri: lb://FRIENDSHIP-SERVICE
      #     predicates:
      #       - Path=/friendships/**

      #   #Cấu hình cổng file comment-service  
      #   - id: comment-service
      #     uri: lb://COMMENT-SERVICE
      #     predicates:
      #       - Path=/comments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Địa chỉ của Eureka Server
  instance:
    prefer-ip-address: true
